### PR TITLE
Generate wrappers for all contracts

### LINKED ISSUE #1889: Auto-generate Python contract wrapper for all remaining contracts (after ERC20Token, Exchange)
## Expected Behavior

Should include doctest examples (or at least minimum viable testing) of all generated wrappers.

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

### PR DESCRIPTION
**Pull request by feuGeneA**
## Description

Fixes #1889 

## Checklist:

-   [x] Enable generation of wrappers for all contracts, in `@0x/python-contract-wrappers`, and include them all in the copying from that package into `python-packages/contract_wrappers`.
-   [x] Fix spurious newline in generated return type for a method with multiple return values.
-   [x] Fix missing definitions for some tuples in `forwarder` and `coordinator`.
-   [x] Fix missing definition for one tuple in `dutch_auction`.  Problem has been identified and described in the commit message for https://github.com/0xProject/0x-monorepo/pull/2010/commits/ea233d7260e28651eecc09a74505322013f88ac5 .
-   [x] Rebase on development, now that #1996 has merged, to ensure there's no further linter issues.  [Update: there wasn't.]
-   [x] Fix tuple classes being used before they're declared.  Need to topologically sort tuples in order to generate declarations in the proper order.
-   [x] Handle overloaded method `safeTransferFrom()`, which is currently resulting in two classes with the same name.  This same problem occurs in both `erc721_token` and `dummy_erc721_token`.
-   [x] Variable name `to`, used in asset proxy and its interface, doesn't conform to pylint naming conventions. specifically, 2 characters is considered too short.
-   [x] Add new entries to the relevant CHANGELOG.jsons.

### CODE REVIEW

**Comment by feuGeneA** [comment]
Upon generating wrappers for all contracts, and running them through the linters, the following problems surfaced:

- summary:
    - Spurious newline in generated return type for a method with multiple return values.
    - Missing definition for some tuples, one in `forwarder`, one in `dutch_auction`, and one in `coordinator`.
    - `forwarder`'s `marketBuyOrdersWithEth.call()` has weird return type `Union[[Tuple0xbb41e5b3, Tuple0xbb41e5b3], Union[HexBytes, bytes]]`
    - Overloaded method `safeTransferFrom()`, in both `erc721_token` and `dummy_erc721_token`, is resutling in two classes with the same name.
- from linter `black`:
    - summary:
        - both of the errors below seem to be a problem with an injected newline when generating a return value type for a method with multiple return values.
    - output:
        ```
        error: cannot format src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py: Cannot parse: 661:97:     def call(self, index_0: int, tx_params: Optional[TxParams] = None) -> [str, int, bytes, bool]
        error: cannot format src/zero_ex/contract_wrappers/order_validator/__init__.py: Cannot parse: 159:138:     def call(self, order: Tuple0x260219a2, taker_address: str, tx_params: Optional[TxParams] = None) -> [Tuple0xb1e4a1ae, Tuple0x8cfc0927]
        ```
- from linter `mypy`:
    - summary:
        - methods returning multiple values need to have return types like `List[typeA, typeB]`, not just `[typeA, typeB]`
        - missing definition for some tuples:
            - `Tuple0x260219a2` in `forwarder`
            - `Tuple0xbb41e5b3` in `dutch_auction`
            - `Tuple0x260219a2` in `coordinator`
        - `forwarder`'s `marketBuyOrdersWithEth.call()` has weird return type `Union[[Tuple0xbb41e5b3, Tuple0xbb41e5b3], Union[HexBytes, bytes]]`
        - erroneous redefinition of `SafeTransferFromMethod` (and attribute `safe_transfer_from`) in both `erc721_token` and `dummy_erc721_token`. looks like it's an overloaded method.
    - output:
        ```
        src/zero_ex/contract_wrappers/order_validator/__init__.py:175: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:243: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:311: error: Invalid type
        src/zero_ex/contract_wrappers/order_validator/__init__.py:511: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:83: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:86: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:152: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:155: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:160: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:214: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:217: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:409: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:411: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:469: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:471: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:476: error: Invalid type
        src/zero_ex/contract_wrappers/forwarder/__init__.py:528: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/forwarder/__init__.py:530: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:557: error: Name 'SafeTransferFromMethod' already defined on line 274
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:754: error: Name 'safe_transfer_from' already defined on line 750
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:127: error: Name 'Tuple0xbb41e5b3' is not defined
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:129: error: Name 'Tuple0xbb41e5b3' is not defined
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:799: error: Name 'SafeTransferFromMethod' already defined on line 374
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:1050: error: Name 'safe_transfer_from' already defined on line 1043
        src/zero_ex/contract_wrappers/coordinator/__init__.py:684: error: Name 'Tuple0x260219a2' is not defined
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:873: error: Invalid type
        ```
- from linter `pylint`:
    - summary:
        - parameters named `to` don't "conform to snake_case naming style"
        - undefinied tuple classes (repeat error from mypy)
        - Overloaded method `safeTransferFrom()`, on both `erc721_token` and `dummy_erc721_token`, generated as two same-named classes (repeat error from mypy)
    - output:
        ```
        ************* Module zero_ex.contract_wrappers.asset_proxy_owner
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:951:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:981:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/asset_proxy_owner/__init__.py:1008:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        ************* Module zero_ex.contract_wrappers.dutch_auction
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:127:10: E0602: Undefined variable 'Tuple0xbb41e5b3' (undefined-variable)
        src/zero_ex/contract_wrappers/dutch_auction/__init__.py:129:11: E0602: Undefined variable 'Tuple0xbb41e5b3' (undefined-variable)
        ************* Module zero_ex.contract_wrappers.coordinator
        src/zero_ex/contract_wrappers/coordinator/__init__.py:684:14: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        ************* Module zero_ex.contract_wrappers.dummy_erc721_token
        src/zero_ex/contract_wrappers/dummy_erc721_token/__init__.py:799:0: E0102: class already defined line 374 (function-redefined)
        ************* Module zero_ex.contract_wrappers.erc721_token
        src/zero_ex/contract_wrappers/erc721_token/__init__.py:557:0: E0102: class already defined line 274 (function-redefined)
        ************* Module zero_ex.contract_wrappers.i_asset_proxy
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:230:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:259:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        src/zero_ex/contract_wrappers/i_asset_proxy/__init__.py:286:4: C0103: Argument name "to" doesn't conform to snake_case naming style (invalid-name)
        ************* Module zero_ex.contract_wrappers.forwarder
        src/zero_ex/contract_wrappers/forwarder/__init__.py:83:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:86:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:152:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:155:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:214:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:217:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:409:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:411:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:469:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:471:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:528:21: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        src/zero_ex/contract_wrappers/forwarder/__init__.py:530:25: E0602: Undefined variable 'Tuple0x260219a2' (undefined-variable)
        ```

File: packages/abi-gen/src/utils.ts [hunk 1]
```diff
@@ -350,4 +350,28 @@ export const utils = {
...
+        parameter: DataItem,
+        tupleDefinitions: { [pythonTupleName: string]: string }, // output
+        tupleDependencies: Array<[string, string]>, // output
+    ): void {
+        if (parameter.type === 'tuple' || parameter.type === 'tuple[]') {
+            const tupleDataItem = parameter as TupleDataItem; // tslint:disable-line:no-unnecessary-type-assertion
+            // without the above cast (which tslint complains about), tsc says
+            //     Argument of type 'DataItem[] | undefined' is not assignable to parameter of type 'DataItem[]'.
+            //     Type 'undefined' is not assignable to type 'DataItem[]'
+            // when the code below tries to access tupleDataItem.components.
```
Comment (fabioberger) [inline packages/abi-gen/src/utils.ts]: Can't you check for `undefined` to get rid of the this error?

File: packages/abi-gen/test-cli/expected-output/python/abi_gen_dummy/__init__.py [hunk 2]
```diff
@@ -54,9 +56,27 @@ class Tuple0xc9bdd2d5(TypedDict):
     accomplished via `str.encode("utf_8")`:code:
     """
 
-    innerStruct: Tuple0xcf8ad995
+    aField: int
+
+
+class Tuple0x1b9da225(TypedDict):
+    """Python representation of a tuple or struct.
```
Comment (xianny) [inline packages/abi-gen/test-cli/expected-output/python/abi_gen_dummy/__init__.py]: Definitely appreciate the usefulness for a detailed comment here.

Suggest some wording changes:


> Solidity compiler output does not include the names of structs that appear in method definitions. Instead, the ABI surfaces the variable name bound in scope. A tuple found in the ABI may have been written in Solidity as an unnamed tuple, or it may have been written as a named struct, but there is no way to tell from the compiler output. This class represents a tuple that appeared in a method definition...

File: packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol [hunk 3]
```diff
@@ -127,6 +127,8 @@ contract AbiGenDummy
     /// @return a Struct struct
     function structOutput() public pure returns(Struct memory s) {}
 
+    function methodReturningArrayOfStructs() public pure returns(Struct[] memory) {}
```
Comment (xianny) [inline packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol]: can we make the naming more consistent somehow?

What about:
```
structOutput
structArrayOutput
```

I also like the effect that alphabetical proximity == conceptual proximity

File: packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol [hunk 4]
```diff
@@ -135,7 +137,28 @@ contract AbiGenDummy
...
+
+    function methodUsingNestedStructWithInnerStructNotUsedElsewhere()
+        public pure returns(NestedStructWithInnerStructNotUsedElsewhere  memory)
+    {}
+
     uint someState;
     function nonPureMethod() public returns(uint) { return someState += 1; }
     function nonPureMethodThatReturnsNothing() public { someState += 1; }
+
+    function methodReturningMultipleValues()
```
Comment (xianny) [inline packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol]: In line with `structOutput` and `structArrayOutput`, maybe this one could be `tupleOutput`?

File: packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol [hunk 5]
```diff
@@ -135,7 +137,28 @@ contract AbiGenDummy
     function nestedStructInput(NestedStruct memory n) public pure {}
     function nestedStructOutput() public pure returns(NestedStruct memory) {}
 
+    struct StructNotDirectlyUsedAnywhere {
```
Comment (xianny) [inline packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol]: suggestion:

```
StructNotInMethodSignatures
StructNotInMethodSignaturesNested | NestedStructNotInMethodSignatures
StructNotInMethodSignaturesNestedOutput
```

I'm not attached to this naming convention, but would like to establish some kind of convention.

Maybe we could use `output/input` for all the method names that test return types? I.e. `<ReturnType>Output` and `<ReturnType>Input`

File: packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol [hunk 6]
```diff
@@ -135,7 +137,28 @@ contract AbiGenDummy
...
     function nonPureMethodThatReturnsNothing() public { someState += 1; }
+
+    function methodReturningMultipleValues()
+        public pure returns (uint256, string memory)
+    {
+        return (1, "hello");
+    }
+
+    function overloadedMethod(int a) public pure {}
+    function overloadedMethod(string memory a) public pure {}
```
Comment (xianny) [inline packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol]: 👍

File: packages/abi-gen/src/utils.ts (hunk 1 above)
Comment (feuGeneA) [reply packages/abi-gen/src/utils.ts]: I'm just being stubborn.  I don't want to say `if` anything at all, because I shouldn't have to.  I created `TupleDataItem`, over in `ethereum-types` (in a prior PR), specifically to have a `DataItem` that _definitely does_ have a `components` field, so that I wouldn't have to do all this checking.  Here, `parameter` is a `DataItem`, but when I see that it has `.type === 'tuple'`, I know it's a `TupleDataItem`, so I cast it.  There *is* a difference between `DataItem` and `TupleDataItem` (the latter _requires_ a `components` field, the former merely permits it), so I assert that there is a bug in `tslint` wherein it's complaining that this cast is unnecessary.  And I like the idea of writing comments to explain the use of in-code linter directives, so I did that.

File: packages/abi-gen/src/index.ts [hunk 7]
```diff
@@ -179,15 +180,18 @@ function registerPythonHelpers(): void {
                 parameters = parameters.concat((abi as MethodAbi).outputs);
             }
             for (const parameter of parameters) {
-                if (parameter.type === 'tuple') {
-                    tupleDefinitions[
-                        utils.makePythonTupleName((parameter as TupleDataItem).components)
-                    ] = utils.makePythonTupleClassBody((parameter as TupleDataItem).components);
-                }
+                utils.extractTuples(parameter, tupleDefinitions, tupleDependencies);
```
[the remark this answers is not in the document]
Comment (feuGeneA) [reply packages/abi-gen/src/index.ts]: I really appreciate this input, but I actually think it's already optimized as you've suggested.  Note that the call to the recursive function `utils.extractTuples()` occurs within a loop, and the body of that loop prior to that call is needed to initialize the parameters to that call, and those state variables are declared right before that loop, and also used subsequent to the loop, so they're already being declared as close to the call as possible.

And, while we could take the approach of wrapping the recursive function with a function that declares the state vars and provides a more intuitive interface, I think the Handlebars helper, `'tupleDefinitions'`, is already playing that role.

To help clarify things, I've added some more comments around these data structures, in https://github.com/0xProject/0x-monorepo/pull/2010/commits/eb9a75cd9a0071ec6e005d778cb26ea3b3b346ef

File: packages/abi-gen/src/index.ts [hunk 8]
```diff
@@ -179,15 +180,18 @@ function registerPythonHelpers(): void {
...
             }
         }
-        const tupleDeclarations = [];
+        const tuplesToDeclare = [];
+        tuplesToDeclare.push(...toposort(tupleDependencies));
```
[the remark this answers is not in the document]
Comment (feuGeneA) [reply packages/abi-gen/src/index.ts]: See https://github.com/0xProject/0x-monorepo/pull/2010/commits/eb9a75cd9a0071ec6e005d778cb26ea3b3b346ef

File: packages/abi-gen/test-cli/expected-output/python/abi_gen_dummy/__init__.py (hunk 2 above)
Comment (feuGeneA) [reply packages/abi-gen/test-cli/expected-output/python/abi_gen_dummy/__init__.py]: See https://github.com/0xProject/0x-monorepo/pull/2010/commits/a12a8a11e6a38d183f8b33b6d57f6ec3276a4dbd

File: packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol (hunk 5 above)
Comment (feuGeneA) [reply packages/abi-gen/test-cli/fixtures/contracts/AbiGenDummy.sol]: Can we punt on establishing some conventions in this contract?  I agree that we definitely should have some more organization here, but it feels out of scope for this PR, especially given the looming milestone deadline.  Feel free to raise a `tech-debt` issue for it :)
